# Generated by Django 2.2.10 on 2020-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('jpg', models.FileField(upload_to='gallery/jpgs')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/photos')),
            ],
        ),
    ]
