# Generated by Django 2.2.10 on 2020-02-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='jpg',
            field=models.FileField(upload_to='gallery/jpgs/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/photos/'),
        ),
    ]
